# Mid  Terms Semesteraufgabe
# Background NUMBAT:
# Datasets show Traveldemand for a day in automn for whole of London, split into 15-min segments
# Data was generated by ticketing-data from smartcards and gateline entry-exits
# Setup: Every 'time'-interval boarding for a line (line boarders), 
#   how many travel on a link, most likely directional (link load),
#   how many entering / exiting a station (Station entry/exit)
#   how many boarding / alighting a station per line and per direction (Station boarders/alighter)
#   numnber of passengers moving points within a station (station link frequency)
#   how many trains per time interval (service frequency)
#   (route choice)  
#   travel time between two stations (journey time)
#   Number of trips by O-D pairing (O/D by network)

# Mögliche Maps: Tagesganglinie für die einzelnen Bahnhöfe
# Boarders In / Out nach Tageszeitpunkt
# Tagesganglinie nach Links

# Library *************************************************************************
library(readxl)
library(tidyverse)
library(viridis)
library(rlang)
library(ggplot2)

# Preperation  **********************************************************************
# Download this file: http://crowding.data.tfl.gov.uk/NUMBAT/NUMBAT%202019/NBT19MTT_Outputs.xlsx

setwd("Desktop/DataanalysisR/data/")

# Functions *************************************************************************
Combine_Different_Stations_By_Name <- function(dataframe_Names15){
  station_name <- "empty"
  Boarders_per_station_combined <- data.frame(matrix(vector(), 0, 15,
                                                     dimnames=list(c(), names(dataframe_Names15))))
  
  for(i in 1 : nrow(dataframe_Names15)){
    if(dataframe_Names15$Station[i] != station_name){
      Boarders_per_station_combined <- rbind(Boarders_per_station_combined, dataframe_Names15[i,])
    } else {
      Boarders_per_station_combined$Total[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$Total[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$Total[i]
      Boarders_per_station_combined$Early[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$Early[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$Early[i]
      Boarders_per_station_combined$`AM Peak`[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$`AM Peak`[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$`AM Peak`[i]
      Boarders_per_station_combined$Midday[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$Midday[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$Midday[i]
      Boarders_per_station_combined$`PM Peak`[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$`PM Peak`[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$`PM Peak`[i]
      Boarders_per_station_combined$Evening[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$Evening[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$Evening[i]
      Boarders_per_station_combined$Late[nrow(Boarders_per_station_combined)] <- Boarders_per_station_combined$Late[nrow(Boarders_per_station_combined)] +
        dataframe_Names15$Late[i]
    }
    station_name <- dataframe_Names15$Station[i]
  }
  
  return(Boarders_per_station_combined)
}

Combine_Different_Stations_By_Departure_Arrival <- function(dataframe_Names24){
  # Order by 'To' Station, hence create data who enters a Station.
  Arrival <- data.frame(matrix(vector(), 0, 24,
                               dimnames=list(c(), names(dataframe_Names24))))
  
  dataframe_Names24 <- dataframe_Names24[order(dataframe_Names24[,6]),]
  for(i in 1 : nrow(dataframe_Names24)){
    if(i == 1){
      Arrival <- Arrival %>% 
        rbind(dataframe_Names24[i,])
      Arrival[i, 5] <- dataframe_Names24[1, 6]
      Arrival[i, 6] <- "To"
    } else {
      # The %in% functionality only works in atomic vectors. Lists may contain multiple kinds of elements, where a vector can only contain one kind of element (f.e. String)
      if(dataframe_Names24[i, 6] %in% unlist(Arrival[,5])) {
        for(time in 7 : 24){
          Arrival[nrow(Arrival), time] <- Arrival[nrow(Arrival), time] + dataframe_Names24[i, time]
        }
      } else {
        Arrival <- Arrival %>% 
          rbind(dataframe_Names24[i,])
        Arrival[nrow(Arrival), 5] <- Arrival[nrow(Arrival), 6]
        Arrival[nrow(Arrival), 6] <- "Arrival"
      }
    }
  }
  
  # Order by 'From' Station  
  Departure <- data.frame(matrix(vector(), 0, 24,
                                 dimnames=list(c(), names(dataframe_Names24))))
  
  dataframe_Names24 <- dataframe_Names24[order(dataframe_Names24[,5]),]
  for(i in 1:nrow(dataframe_Names24)){
    if(i == 1){
      Departure <- Departure %>% 
        rbind(dataframe_Names24[i,])
      Departure[i, 6] <- "Moving_Away_From_Station"
    } else {
      if(dataframe_Names24[i, 5] %in% unlist(Departure[,5])) {
        for(time in 7 : 24){
          Departure[nrow(Departure), time] <- Departure[nrow(Departure), time] + dataframe_Names24[i, time]
        }
      }else{
        Departure <- Departure %>% 
          rbind(dataframe_Names24[i,])
        Departure[nrow(Departure), 6] <- "Departure"
      }
    }
  }
  
  Arrival_Departure <- Arrival %>% 
    rbind(Departure)
  
  colnames(Arrival_Departure)[5] <- "Station"
  colnames(Arrival_Departure)[6] <- "Direction"
  return(Arrival_Departure)
}


#   Boarders *************************************************************************
NBT19MTT_Outputs_Boarders <- read_excel("NBT19MTT_Outputs.xlsx", 
                                    sheet = "Station_Boarders", skip = 2)
Boarders_per_station <- NBT19MTT_Outputs_Boarders[,1:15]
# Kumulierte Stationen 455 Stationen
remove(NBT19MTT_Outputs_Boarders)
Boarders_per_station_combined <- Combine_Different_Stations_By_Name(Boarders_per_station)
remove(Boarders_per_station)

#   Alighter **************************************************************************
NBT19MTT_Outputs_Alighters <- read_excel("NBT19MTT_Outputs.xlsx", 
                                    sheet = "Station_Alighters", skip = 2)
Alighters_per_station <- NBT19MTT_Outputs_Alighters[, 1: 15]
remove(NBT19MTT_Outputs_Alighters)
Alighters_per_station_combined <- Combine_Different_Stations_By_Name(Alighters_per_station)
remove(Alighters_per_station)

# Comnbining Boarders and Alighers *****************************************************
Boarders_Shortend <- select(Boarders_per_station_combined, Station, Total, Early,`AM Peak`, Midday, `PM Peak`, Evening, Late)
Alighters_Shortend <- select(Alighters_per_station_combined, Station, Total, Early,`AM Peak`, Midday, `PM Peak`, Evening, Late)
Boarders_Alighters_per_station <- merge(Boarders_Shortend, Alighters_Shortend, by = "Station",
                                            suffix=c("_Boarders", "_Alighters"))
remove(Boarders_per_station_combined)
remove(Alighters_per_station_combined)

#   Entrances **************************************************************************
NBT19MTT_Outputs_Entries <- read_excel("NBT19MTT_Outputs.xlsx", 
                                         sheet = "Station_Entries", skip = 2)
Entrances_per_station <- NBT19MTT_Outputs_Entries[, 1: 11]
remove(NBT19MTT_Outputs_Entries)

#   Exits ******************************************************************************
NBT19MTT_Outputs_Exits <- read_excel("NBT19MTT_Outputs.xlsx", 
                                       sheet = "Station_Exits", skip = 2)
Exits_per_station <- NBT19MTT_Outputs_Exits[, 1: 11]
remove(NBT19MTT_Outputs_Exits)

# Combining Exits and Entrances ********************************************************
Entrances_shortend <- select(Entrances_per_station, Station, Total, Early,`AM Peak`, Midday, `PM Peak`, Evening, Late)
Exits_shortend <- select(Exits_per_station, Station, Total, Early,`AM Peak`, Midday, `PM Peak`, Evening, Late)
Entrances_Exits_per_station <- merge(Entrances_shortend, Exits_shortend, by = "Station", suffix=c("_Entrance", "_Exit"))
remove(Entrances_per_station)
remove(Exits_per_station)

# Combining Boarders/Alighters and Entrances/Exits ************************************
Boarders_Shortend <- Boarders_Shortend %>% mutate(Activity_type = "Boarder")
Alighters_Shortend <- Alighters_Shortend %>% mutate(Activity_type = "Alighter")
Entrances_shortend <- Entrances_shortend %>% mutate(Activity_type = "Entrance")
Exits_shortend <- Exits_shortend %>% mutate(Activity_type = "Exit")

Boarders_Alighters_Entrances_Exits_per_Station <- Boarders_Shortend %>% 
  rbind(Alighters_Shortend) %>% 
  rbind(Entrances_shortend) %>% 
  rbind(Exits_shortend)


#   Link Loads *************************************************************************
NBT19MTT_Outputs_LinkLoads <- read_excel("NBT19MTT_Outputs.xlsx", 
                                              sheet = "Link_Loads", skip = 2)
# Begrenzt die Uhrzeiten zwischen 5:00 und 22:00 Uhr
NBT19MTT_Outputs_LinkLoads <- NBT19MTT_Outputs_LinkLoads[,1:89]
ncol_LinksLoaded <- ncol(NBT19MTT_Outputs_LinkLoads)

time_counter <- 18
while(time_counter < ncol_LinksLoaded) {
  # Automatically determins the time.
  if(((time_counter-18) %/% 4) < 5){
    selectedTime <- paste("0", (time_counter - 18) %/% 4 + 5, "_o'clock", sep = "")
  } else {
    selectedTime <- paste((time_counter - 18) %/% 4 + 5, "_o'clock", sep = "")
  }
  NBT19MTT_Outputs_LinkLoads <- NBT19MTT_Outputs_LinkLoads %>% 
    mutate(!!paste(selectedTime) := 0)
  for(i in 1: nrow(NBT19MTT_Outputs_LinkLoads)){
    # [<- can assign with evaluating. $ does not evaluate the statement afterwards.
    NBT19MTT_Outputs_LinkLoads[i,] <- data.frame(`[<-`(NBT19MTT_Outputs_LinkLoads[i,], selectedTime, value = as.integer
                                                       (sum(NBT19MTT_Outputs_LinkLoads[i,time_counter:(time_counter+3)]))))
  }
  time_counter <- time_counter + 4
}
LinkLoads_Shortend <- NBT19MTT_Outputs_LinkLoads[, c(1:4, 7, 10 ,90:107)]
Arrival_Departure_per_Station <- Combine_Different_Stations_By_Departure_Arrival(LinkLoads_Shortend)
remove(NBT19MTT_Outputs_LinkLoads)


# Plotting *************************************************************************
Boarders_Alighters_per_station %>% 
  filter(Station %in% c("Brixton LU", "Bond Street", "Canary Wharf LU", "Chancery Lane")) %>%  
  pivot_longer(c(Early_Boarders, `AM Peak_Boarders`, Midday_Boarders, `PM Peak_Boarders`, Evening_Boarders, Late_Boarders,
                 Early_Alighters, `AM Peak_Alighters`, Midday_Alighters, `PM Peak_Alighters`, Evening_Alighters, Late_Alighters), names_to = "Time of day", values_to = "count_by_Daytime") %>%
  rowwise() %>% mutate(Activity_type = strsplit(`Time of day`, split="_")[[1]][2]) %>%
  rowwise() %>% mutate(`Time of day` = strsplit(`Time of day`, split="_")[[1]][1]) %>% 
  ggplot(aes(y=count_by_Daytime, x=Activity_type, fill = `Time of day`)) +
    geom_bar(stat="identity") + 
    theme(axis.text.x = element_text(size = 9.5), title = element_text(size=18), plot.subtitle = element_text(size=16),
        plot.caption = element_text(size=10.5), axis.text.y = element_text(size = 9.5), axis.title = element_text(size = 15.5),
        legend.text = element_text(size = 12)) +
    scale_fill_viridis(discrete = TRUE, direction = -1) +
    labs(title = "Boarders and Alighters, divided into time of day.",
       subtitle = "Selected stations.",
       color="",
       caption="data source: NBT19MTT_Outputs.xlsx\n from: http://crowding.data.tfl.gov.uk")+
    facet_wrap(~Station)

Boarders_Alighters_Entrances_Exits_per_Station %>% 
  filter(Station %in% c("Brixton LU", "Bond Street", "Canary Wharf LU", "Chancery Lane")) %>%  
  ggplot(aes(x="", y= `AM Peak`, fill = Activity_type)) +
    geom_bar(stat="identity", width=1, color="white", position=position_fill()) +
    theme(plot.title = element_text(size=18), plot.subtitle = element_text(size=16),
        plot.caption = element_text(size=10.5), axis.title = element_text(size = 15.5),
        legend.text = element_text(size = 12)) +
    scale_color_viridis() +
    coord_polar(theta="y") +
    theme_void() +
    scale_fill_viridis(discrete = TRUE, direction = -1) +
    labs(title = "Number of Boarders, Alighters, Entries and Exits",
       subtitle = "Selected stations for the morning Peak (7:00 am to 10:00 am).",
       color="",
       caption="data source: NBT19MTT_Outputs.xlsx\n from: http://crowding.data.tfl.gov.uk")+
    facet_wrap(~Station)

Arrival_Departure_per_Station %>% 
  filter(`Station` %in% c("Brixton LU", "Bond Street", "Canary Wharf LU", "Chancery Lane")) %>%
  pivot_longer(c(7:24), names_to = "Time of day", values_to = "Load") %>% 
  ggplot(aes(x=`Time of day`, y= `Load`, group = `Direction`)) +
    geom_line(stat="identity", aes(color=`Direction`)) +
    theme(axis.text.x = element_text(angle = 45, size = 9.5), title = element_text(size=18), plot.subtitle = element_text(size=16),
          plot.caption = element_text(size=10.5), axis.text.y = element_text(size = 9.5), axis.title = element_text(size = 15.5),
          legend.text = element_text(size = 12)) +
    scale_color_viridis(discrete = TRUE, end = 0.7) +
    labs(title = "Daily load curve, divided into Arrivals and Departures",
         subtitle = "Selected stations for the time interval 5:00 am to 11:00 pm.",
         color="",
         caption = "data source: NBT19MTT_Outputs.xlsx\n from: http://crowding.data.tfl.gov.uk")+
    facet_wrap(~Station)

